name: Run Unit Tests

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 8.0.x
        - name: Restore dependencies
          run: |
            dotnet restore S.O.F.I.S/S.O.F.I.S.csproj
            dotnet restore S.O.F.I.S/Tests/S.O.F.I.S.Tests.csproj

        - name: Build solution
          run: dotnet test Tests/S.O.F.I.S.Tests.csproj --no-build --verbosity normal

    docker-test:
        runs-on: ubuntu-latest
        needs:  test

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build Docker image
          run: |
            cd S.O.F.I.S
            docker build -t sofis-api .

        - name: Run containerized tests
          run: |
            docker run --rm sofis-api dotnet test
